baseURL = "https://gyuha.com/"
languageCode = "ko-KR"
title = "신규하 블로그"
theme = "hago"

DefaultContentLanguage = "kr"
metaDataFormat = "yaml"
disqusShortname = "gyuha-blog"
paginate = 7


[Params]
  description = "Gyuha blog"
  subtitle = "개발 기록 보관소"
  logo = "/img/logo-title.png"
  favicon = "/favicon.ico"
  comments = true
  
[pygmentsOptions]
  linenos = "table"
  pygmentsOptions = "table"

[Author]
  name = "신규하"
  website = "https://gyuha.com"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "fruity"
    tabWidth = 2

[Services]
  [Services.GoogleAnalytics]
    ID = "G-3XN21838ZJ"