baseURL = "https://gyuha.github.io/"
languageCode = "ko-KR"
title = "신규하 블로그"
theme = "hago"

DefaultContentLanguage = "kr"
metaDataFormat = "yaml"
disqusShortname = "gyuha-blog"
googleAnalytics = "UA-128878421-1"
paginate = 4


[Params]
  description = "Gyuha blog"
  subtitle = "개발 기록 보관소"
  logo = "/img/logo-title.png"
  favicon = "/favicon.ico"
  comments = true

[Author]
  name = "신규하"
  website = "https://gyuha.github.io"
