baseURL = "https://gyuha.github.io/"
languageCode = "ko-KR"
title = "Gyuha Blog"

DefaultContentLanguage = "kr"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "gyuha-blog"
googleAnalytics = "UA-128878421-1"
paginate = 7


[Params]
  description = "Gyuha blog"
  subtitle = "개발 하면서 기록하는 생활의 기록..."
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  showRelatedPosts = true

[Author]
  name = "신규하"
  website = "https://gyuha.github.io"
  facebook = "gyuha.shin"
  github = "gyuha"
  gitlab = "nicegyuha"
  twitter = "gyuha"
