# theme.toml template for a Hugo theme

name = "Hago"
license = "MIT"
licenselink = "https://github.com/gyuha/haru-hago-theme/blob/master/LICENSE.md"
description = "Blog theme"
homepage = "https://github.com/gyuha/hugo-hago-theme/"
tags = ["blog", "theme"]
features = ["blog", "simple"]
min_version = 0.15

[author]
  name = "gyuha"
  homepage = "https://gyuha.github.io"
